apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}
stringData:
  user: {{ .Values.backendAdminUsername }}
  password: {{ .Values.backendAdminPassword }}
type: Opaque
