apiVersion: v1
kind: Service
metadata:
  name: sensu
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ $.Chart.Name }}
  clusterIP: None
  ports:
  - name: sensu-etcd-client
    port: 2379
  - name: sensu-etcd-server
    port: 2380
---
apiVersion: v1
kind: Service
metadata:
  name: sensu-lb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ $.Chart.Name }}
  type: NodePort
  ports:
  - name: sensu-api
    protocol: TCP
    port: 8080
    targetPort: 8080
{{- if (not (empty .Values.sensu.nodePortApi)) }}
    nodePort: {{.Values.sensu.nodePortApi}}
{{- end }}
  - name: sensu-transport
    protocol: TCP
    port: 8081
    targetPort: 8081
{{- if (not (empty .Values.sensu.nodePortTransport)) }}
    nodePort: {{.Values.sensu.nodePortTransport}}
{{- end }}
  - name: sensu-webui
    protocol: TCP
    port: 80
    targetPort: 3000
{{- if (not (empty .Values.sensu.nodePortWebUI)) }}
    nodePort: {{.Values.sensu.nodePortWebUI}}
{{- end }}