apiVersion: v1
kind: Secret
metadata:
  name: backend-certs
  namespace: {{ .Values.namespace }}
stringData:
  backend-key.pem: |-
    -----BEGIN RSA PRIVATE KEY-----
    ....
    ....
    ....
    -----END RSA PRIVATE KEY-----
  backend.pem: |-
    -----BEGIN CERTIFICATE-----
    ....
    ....
    ....
    -----END CERTIFICATE-----
  ca.pem: |-
    -----BEGIN CERTIFICATE-----
    ....
    ....
    ....
    -----END CERTIFICATE-----
type: Opaque
